name: Python application

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Pre-commit checks
      run: |
        python -m pip install pre-commit
        pre-commit run --all-files

    # TODO in the future
    # - name: Sphinx documentation build
    #   run: |
    #     python -m pip install sphinx
    #     sphinx-build -b html docs/ docs/_build/

    # - name: Build and push Docker image
    #   uses: docker/build-push-action@v2
    #   with:
    #     context: .
    #     push: true
    #     tags: username/qtmlib:latest